services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - weather-net

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - REDIS_HOST=redis
    networks:
      - weather-net
    depends_on:
      - redis

networks:
  weather-net: